### ISSUE TITLE
rule: no unused layer names

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/stylelint-plugin#16]
```css
@layer reset, utilities;
/* ---------------^   */

@layer reset {
  * {
    margin: 0;
  }
}
```

`utilities` is declared but never used.
