### ISSUE TITLE
rule: no anonymous/unnamed layers

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/stylelint-plugin#17]
```css
@layer reset, utilities;

@layer {
/* ---^ */
  * {
    margin: 0;
  }
}
```
