### ISSUE TITLE
rule: no-undeclared-container-names

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/stylelint-plugin#8]
```css
@container --unknown {
/* --------^ */
  * {
    margin: 0;
  }
}
```

- add allowList (array of `String|RegExp`) to allow certain container names that were never defined
- add to root readme table and config example
- add readme for rule
- add tests
